services:


  backend1:
    build: ./backend1
    restart: always
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 5s
      timeout: 2s
      retries: 3
 
  backend2:
    build: ./backend2
    restart: always
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 5s
      timeout: 2s
      retries: 3



  nginx:
    image: nginx:alpine
 
    ports:
      - "8085:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro

    depends_on:
      - backend1
      - backend2

